apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: eda0a53085d4875fbd5b17bde3654e225f5b3379
  application.deploy.reform/deploymentNo: har-smoke2-local_DP1
  application.deploy.reform/environment: local
  application.deploy.reform/name: har-smoke2
  application.deploy.reform/repository: https://github.com/Gglayolun/smoketest.git
  application.deploy.reform/repositoryPath: har-smoke2
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: f0b71db77f6a0f746bcd4186d01868e6a404cbc0
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
