apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 5c6d797dfa7d639de29835ba9e4260fb240fdb15
  application.deploy.reform/deploymentNo: harr-1-local_DP4
  application.deploy.reform/environment: local
  application.deploy.reform/name: harr-1
  application.deploy.reform/repository: https://github.com/Gglayolun/smoketest.git
  application.deploy.reform/repositoryPath: harr-1
  application.deploy.reform/revision: 2023.04.4-RB2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: f0b71db77f6a0f746bcd4186d01868e6a404cbc0
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
