apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 1dc211c68a25263a0b1d71d178f631e179ad9960
  application.deploy.reform/deploymentNo: harris-smoke1-local_DP5
  application.deploy.reform/environment: local
  application.deploy.reform/name: harris-smoke1
  application.deploy.reform/repository: https://github.com/Gglayolun/smoketest.git
  application.deploy.reform/repositoryPath: harris-smoke1
  application.deploy.reform/revision: 2023.04.5
  deploy.reform/domain: ""
  deploy.reform/version: f0b71db77f6a0f746bcd4186d01868e6a404cbc0
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
