apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 66623109b031bc5b0021f68c82a6258d7a2753b6
  application.deploy.reform/deploymentNo: harris-smoke1-local_DP1
  application.deploy.reform/environment: local
  application.deploy.reform/name: harris-smoke1
  application.deploy.reform/repository: https://github.com/Gglayolun/smoketest.git
  application.deploy.reform/repositoryPath: harris-smoke1
  application.deploy.reform/revision: 2023.04.1
  deploy.reform/domain: ""
  deploy.reform/version: f0b71db77f6a0f746bcd4186d01868e6a404cbc0
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
