apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 45ee4422e0393da8c542be720e5ea4e4befa4355
  application.deploy.reform/deploymentNo: har2smoke-local-approval_DP2
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: har2smoke
  application.deploy.reform/repository: https://github.com/Gglayolun/smoketest.git
  application.deploy.reform/repositoryPath: har2smoke
  application.deploy.reform/revision: 2023.04.2
  deploy.reform/domain: ""
  deploy.reform/version: f0b71db77f6a0f746bcd4186d01868e6a404cbc0
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
