apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  application.deploy.reform/cluster: local
  application.deploy.reform/commitHash: 3bcfded708de5974a90988fb011db790bd256fdd
  application.deploy.reform/deploymentNo: har2smoke-local-approval_DP36
  application.deploy.reform/environment: local-approval
  application.deploy.reform/name: har2smoke
  application.deploy.reform/repository: https://github.com/Gglayolun/smoketest.git
  application.deploy.reform/repositoryPath: har2smoke
  application.deploy.reform/revision: 2023.04.36-RB2023.04.3
  deploy.reform/domain: ""
  deploy.reform/version: 8bb007025bbf81bb8a6773ddf5e940e16c00bf22
kind: Kustomization
namespace: vela-app
patchesStrategicMerge:
- application.yaml
resources:
- ../../base
